package de.elmar_baumann.imv.view.panels;

import de.elmar_baumann.imv.data.AutoCompleteDataOfColumn;
import de.elmar_baumann.imv.data.TextEntry;
import de.elmar_baumann.imv.data.TextEntryContent;
import de.elmar_baumann.imv.database.metadata.Column;
import de.elmar_baumann.imv.datatransfer.TransferHandlerDropEdit;
import de.elmar_baumann.imv.event.listener.TextEntryListener;
import de.elmar_baumann.imv.event.listener.impl.TextEntryListenerSupport;
import de.elmar_baumann.imv.resource.Bundle;
import de.elmar_baumann.lib.componentutil.InputVerifierMaxLength;
import de.elmar_baumann.lib.component.TabOrEnterLeavingTextArea;
import java.awt.Color;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 * Panel zum Eingeben einzeiliger Texte.
 * 
 * @author  Elmar Baumann <eb@elmar-baumann.de>
 * @version 2008-09-18
 */
public final class EditTextEntryPanel
        extends javax.swing.JPanel
        implements TextEntry, DocumentListener {

    private static final Color EDITABLE_COLOR = Color.WHITE;
    private Column column;
    private boolean dirty = false;
    private boolean editable;
    private TextEntryListenerSupport textEntryListenerSupport =
            new TextEntryListenerSupport();

    public EditTextEntryPanel(Column column) {
        this.column = column;
        initComponents();
        postInitComponents();
    }

    private void postInitComponents() {
        setPropmt();
        textAreaEdit.setInputVerifier(
                new InputVerifierMaxLength(column.getLength()));
        textAreaEdit.getDocument().addDocumentListener(this);
    }

    private void setPropmt() {
        labelPrompt.setText(column.getDescription());
    }

    @Override
    public String getText() {
        return textAreaEdit.getText().trim();
    }

    @Override
    public boolean isDirty() {
        return dirty;
    }

    @Override
    public void setDirty(boolean dirty) {
        this.dirty = dirty;
    }

    @Override
    public void setText(String text) {
        textAreaEdit.setText(text.trim());
        dirty = false;
    }

    @Override
    public void empty(boolean dirty) {
        textAreaEdit.setText(""); // NOI18N
        this.dirty = dirty;
    }

    @Override
    public Column getColumn() {
        return column;
    }

    @Override
    public void setAutocomplete() {
        AutoCompleteDecorator.decorate(
                textAreaEdit,
                AutoCompleteDataOfColumn.INSTANCE.get(column).getData(),
                false);
    }

    @Override
    public boolean isEmpty() {
        return textAreaEdit.getText().isEmpty();
    }

    @Override
    public void focus() {
        textAreaEdit.requestFocus();
    }

    @Override
    public void setEditable(boolean editable) {
        this.editable = editable;
        textAreaEdit.setEditable(editable);
        textAreaEdit.setBackground(editable
                                   ? EDITABLE_COLOR
                                   : getBackground());
    }

    @Override
    public boolean isEditable() {
        return editable;
    }

    @Override
    public TextEntry clone() {
        return new TextEntryContent(getText(), column);
    }

    @Override
    public void insertUpdate(DocumentEvent e) {
        notifyTextChanged(column, "", textAreaEdit.getText()); // NOI18N
        dirty = true;
    }

    @Override
    public void removeUpdate(DocumentEvent e) {
        notifyTextChanged(column, "", textAreaEdit.getText()); // NOI18N
        dirty = true;
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
        notifyTextChanged(column, "", textAreaEdit.getText()); // NOI18N
        dirty = true;
    }

    public void addTextEntryListener(TextEntryListener listener) {
        textEntryListenerSupport.addTextEntryListener(listener);
    }

    public void removeTextEntryListener(TextEntryListener listener) {
        textEntryListenerSupport.removeTextEntryListener(listener);
    }

    private void notifyTextChanged(Column column, String oldText, String newText) {
        textEntryListenerSupport.notifyTextChanged(column, oldText, newText);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelPrompt = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        textAreaEdit = textAreaEdit = new TabOrEnterLeavingTextArea();

        setLayout(new java.awt.GridBagLayout());

        labelPrompt.setText(Bundle.getString("EditTextEntryPanel.labelPrompt.text")); // NOI18N
        labelPrompt.setToolTipText(column.getLongerDescription());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        add(labelPrompt, gridBagConstraints);

        textAreaEdit.setColumns(1);
        textAreaEdit.setLineWrap(true);
        textAreaEdit.setRows(1);
        scrollPane.setViewportView(textAreaEdit);
        textAreaEdit.setTransferHandler(new TransferHandlerDropEdit());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.5;
        add(scrollPane, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelPrompt;
    private javax.swing.JScrollPane scrollPane;
    public javax.swing.JTextArea textAreaEdit;
    // End of variables declaration//GEN-END:variables
}
