package org.jphototagger.image.thumbnail;

import java.io.File;

import javax.swing.JFileChooser;

import org.openide.util.Lookup;

import org.jphototagger.api.preferences.Preferences;
import org.jphototagger.image.ImagePreferencesKeys;
import org.jphototagger.lib.swing.FileChooserHelper;
import org.jphototagger.lib.swing.FileChooserProperties;
import org.jphototagger.lib.swing.IconUtil;
import org.jphototagger.lib.swing.util.MnemonicUtil;
import org.jphototagger.lib.util.Bundle;
import org.jphototagger.lib.util.StringUtil;

/**
 * @author Elmar Baumann
 */
public class DcrawThumbnailCreatorSettingsPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    public DcrawThumbnailCreatorSettingsPanel() {
        initComponents();
        postInitComponents();
    }

    private void postInitComponents() {
        MnemonicUtil.setMnemonics(this);
        readPreferences();
        buttonRemoveFile.setEnabled(StringUtil.hasContent(labelFile.getText()));
    }

    private void chooseFile() {
        FileChooserProperties props = createFileChooserProperties();
        File dcraw = FileChooserHelper.chooseFile(props);
        if (dcraw != null) {
            labelFile.setText(dcraw.getAbsolutePath());
            labelFile.setIcon(IconUtil.getSystemIcon(dcraw));
            buttonRemoveFile.setEnabled(true);
            persistFile();
        }
    }

    private FileChooserProperties createFileChooserProperties() {
        FileChooserProperties props = new FileChooserProperties();
        props.currentDirectoryPath(getDirectoryPath());
        props.dialogTitle(Bundle.getString(DcrawThumbnailCreatorSettingsPanel.class, "DcrawThumbnailCreatorSettingsPanel.FileChooser.Title"));
        props.multiSelectionEnabled(false);
        props.fileSelectionMode(JFileChooser.FILES_ONLY);
        props.propertyKeyPrefix("DcrawThumbnailCreatorPanel.FileChooser");
        return props;
    }

    private String getDirectoryPath() {
        File file = new File(labelFile.getText());
        if (file.isFile()) {
            String parent = file.getParent();
            return parent == null ? "" : parent;
        }
        return "";
    }

    private void removeFile() {
        labelFile.setText("");
        buttonRemoveFile.setEnabled(false);
        persistFile();
    }

    private void persistFile() {
        Preferences prefs = Lookup.getDefault().lookup(Preferences.class);
        String filepath = labelFile.getText();
        if (StringUtil.hasContent(filepath)) {
            prefs.setString(ImagePreferencesKeys.KEY_DCRAW_FILEPATH, filepath);
        } else {
            prefs.removeKey(ImagePreferencesKeys.KEY_DCRAW_FILEPATH);
        }
    }

    private void readPreferences() {
        Preferences prefs = Lookup.getDefault().lookup(Preferences.class);
        if (prefs.containsKey(ImagePreferencesKeys.KEY_DCRAW_FILEPATH)) {
            File file = new File(prefs.getString(ImagePreferencesKeys.KEY_DCRAW_FILEPATH));
            labelFile.setText(file.getAbsolutePath());
            labelFile.setIcon(file.isFile()
                    ? IconUtil.getSystemIcon(file)
                    : IconUtil.getImageIcon(DcrawThumbnailCreatorSettingsPanel.class, "error.png"));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        labelInfo = new javax.swing.JLabel();
        panelChooseFile = new javax.swing.JPanel();
        labelFile = new javax.swing.JLabel();
        buttonChooseFile = new javax.swing.JButton();
        buttonRemoveFile = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jphototagger/image/thumbnail/Bundle"); // NOI18N
        setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("DcrawThumbnailCreatorSettingsPanel.border.title"))); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        labelInfo.setText(bundle.getString("DcrawThumbnailCreatorSettingsPanel.labelInfo.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(labelInfo, gridBagConstraints);

        panelChooseFile.setLayout(new java.awt.GridBagLayout());

        labelFile.setText(" "); // NOI18N
        labelFile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        panelChooseFile.add(labelFile, gridBagConstraints);

        buttonChooseFile.setText(bundle.getString("DcrawThumbnailCreatorSettingsPanel.buttonChooseFile.text")); // NOI18N
        buttonChooseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChooseFileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        panelChooseFile.add(buttonChooseFile, gridBagConstraints);

        buttonRemoveFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jphototagger/image/thumbnail/delete.png"))); // NOI18N
        buttonRemoveFile.setEnabled(false);
        buttonRemoveFile.setMargin(new java.awt.Insets(2, 2, 2, 2));
        buttonRemoveFile.setPreferredSize(new java.awt.Dimension(18, 18));
        buttonRemoveFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveFileActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        panelChooseFile.add(buttonRemoveFile, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 5, 5);
        add(panelChooseFile, gridBagConstraints);
    }//GEN-END:initComponents

    private void buttonChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChooseFileActionPerformed
        chooseFile();
    }//GEN-LAST:event_buttonChooseFileActionPerformed

    private void buttonRemoveFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveFileActionPerformed
        removeFile();
    }//GEN-LAST:event_buttonRemoveFileActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonChooseFile;
    private javax.swing.JButton buttonRemoveFile;
    private javax.swing.JLabel labelFile;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JPanel panelChooseFile;
    // End of variables declaration//GEN-END:variables
}
