/*
 * @(#)PopupPanel.java    Created on 2010-14-10
 *
 * Copyright (C) 2009-2010 by the JPhotoTagger developer team.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA  02110-1301, USA.
 */
package org.jphototagger.program.view.panels;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.Popup;

/**
 * Panel for usage as {@link Popup}.
 *
 * @author Elmar Baumann
 */
public class PopupPanel extends javax.swing.JPanel {
    private static final long serialVersionUID = 697077008966184390L;

    /**
     * Constructur with a popup message.
     *
     * @param message message, can be HTML formatted
     */
    public PopupPanel(String message) {
        initComponents();

        labelMessage.setText(message);

        setPreferredSize(labelMessage.getPreferredSize());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelMessage = new javax.swing.JLabel();

        setBackground(ThumbnailsPanel.COLOR_BACKGROUND_PANEL);
        setForeground(ThumbnailsPanel.COLOR_FOREGROUND_PANEL);
        setOpaque(false);

        labelMessage.setBackground(ThumbnailsPanel.COLOR_BACKGROUND_PANEL);
        labelMessage.setForeground(ThumbnailsPanel.COLOR_FOREGROUND_PANEL);
        labelMessage.setText("Info"); // NOI18N
        labelMessage.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelMessage;
    // End of variables declaration//GEN-END:variables

}
