package org.jphototagger.program.view.panels;

import java.text.MessageFormat;

import org.openide.util.Lookup;

import org.jphototagger.api.file.FilenameTokens;
import org.jphototagger.domain.repository.FileRepositoryProvider;
import org.jphototagger.lib.awt.EventQueueUtil;
import org.jphototagger.lib.util.Bundle;
import org.jphototagger.program.model.RepositoryInfoTableModel;
import org.jphototagger.program.view.renderer.RepositoryInfoColumnsTableCellRenderer;

/**
 *
 * @author Elmar Baumann
 */
public final class RepositoryInfoCountPanel extends javax.swing.JPanel {
    private static final long  serialVersionUID = -8537559082830438692L;
    private RepositoryInfoTableModel repositoryInfoTableModel;
    private volatile boolean listenToDbChanges;

    public RepositoryInfoCountPanel() {
        initComponents();
        table.setDefaultRenderer(Object.class, new RepositoryInfoColumnsTableCellRenderer());
        setLabelFilename();
    }

    public void listenToRepositoryChanges(boolean listen) {
        listenToDbChanges = listen;

        if (listen) {
            setModelRepositoryInfo();
        }

        if (repositoryInfoTableModel != null) {
            repositoryInfoTableModel.setListenToRepository(listen);
        }
    }

    private void setLabelFilename() {
        String pattern = Bundle.getString(RepositoryInfoCountPanel.class, "RepositoryInfoCountPanel.labelFilename.Filename");
        FileRepositoryProvider provider = Lookup.getDefault().lookup(FileRepositoryProvider.class);

        if (provider != null) {
            String repositoryFileName = provider.getFileRepositoryFileName(FilenameTokens.FULL_PATH);
            String message = MessageFormat.format(pattern, repositoryFileName);

            labelFilename.setText(message);
        }
    }

    private void setModelRepositoryInfo() {
        if (repositoryInfoTableModel == null) {
            Thread thread = new Thread(new Runnable() {

                @Override
                public void run() {
                    EventQueueUtil.invokeInDispatchThread(new Runnable() {

                        @Override
                        public void run() {
                            repositoryInfoTableModel = new RepositoryInfoTableModel();
                            repositoryInfoTableModel.setListenToRepository(listenToDbChanges);
                            table.setModel(repositoryInfoTableModel);
                            repositoryInfoTableModel.update();
                        }
                    });
                }
            }, "JPhotoTagger: Updating repository info");

            thread.start();
        } else {
            repositoryInfoTableModel.setListenToRepository(true);
            repositoryInfoTableModel.update();
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        labelTable = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        labelFilename = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jphototagger/program/view/panels/Bundle"); // NOI18N
        labelTable.setText(bundle.getString("RepositoryInfoCountPanel.labelTable.text")); // NOI18N
        labelTable.setName("labelTable"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 12);
        add(labelTable, gridBagConstraints);

        scrollPane.setName("scrollPane"); // NOI18N

        table.setName("table"); // NOI18N
        scrollPane.setViewportView(table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 12);
        add(scrollPane, gridBagConstraints);

        labelFilename.setText(bundle.getString("RepositoryInfoCountPanel.labelFilename.text")); // NOI18N
        labelFilename.setName("labelFilename"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 12, 12);
        add(labelFilename, gridBagConstraints);
    }//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelFilename;
    private javax.swing.JLabel labelTable;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
