package org.jphototagger.program.view.panels;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.jphototagger.lib.componentutil.MnemonicUtil;
import org.jphototagger.lib.event.util.MouseEventUtil;
import org.jphototagger.program.app.MessageDisplayer;
import org.jphototagger.program.data.UserDefinedFileType;
import org.jphototagger.program.database.DatabaseUserDefinedFileTypes;
import org.jphototagger.program.model.ListModelUserDefinedFileTypes;
import org.jphototagger.program.resource.JptBundle;
import org.jphototagger.program.view.dialogs.EditUserDefinedFileTypeDialog;

/**
 *
 *
 * @author Elmar Baumann
 */
public class UserDefinedFileTypesPanel extends javax.swing.JPanel {
    private static final long serialVersionUID = -7747694022574930356L;

    public UserDefinedFileTypesPanel() {
        initComponents();
        postInitComponents();
    }

    private void postInitComponents() {
        MnemonicUtil.setMnemonics(this);
        list.addListSelectionListener(new ButtonEnabler());
    }

    private void addUserDefinedFileType() {
        EditUserDefinedFileTypeDialog dlg = new EditUserDefinedFileTypeDialog();

        dlg.setVisible(true);
    }

    private void editUserDefinedFileType() {
        List<UserDefinedFileType> fileTypes = getSelectedUserDefinedFileTypes();

        for (UserDefinedFileType fileType : fileTypes) {
            EditUserDefinedFileTypeDialog dlg = new EditUserDefinedFileTypeDialog();

            dlg.setUserDefinedFileType(fileType);
            dlg.setVisible(true);
        }
    }

    private void deleteUserDefinedFileType() {
        if (MessageDisplayer.confirmYesNo(this, "UserDefinedFileTypesPanel.Confirm.Delete")) {
            List<UserDefinedFileType> fileTypes = getSelectedUserDefinedFileTypes();

            for (UserDefinedFileType fileType : fileTypes) {
                DatabaseUserDefinedFileTypes.INSTANCE.delete(fileType);
            }
        }
    }

    private void editClickedUserDefinedFileType(MouseEvent evt) {
        if (MouseEventUtil.isDoubleClick(evt)) {
            editUserDefinedFileType();
        }
    }

    private List<UserDefinedFileType> getSelectedUserDefinedFileTypes() {
        List<UserDefinedFileType> fileTypes = new ArrayList<UserDefinedFileType>();

        for (Object selectedValue : list.getSelectedValues()) {
            if (selectedValue instanceof UserDefinedFileType) {
                fileTypes.add((UserDefinedFileType) selectedValue);
            }
        }

        return fileTypes;
    }

    private boolean isListItemSelected() {
        int selectedIndex = list.getSelectedIndex();

        return selectedIndex >= 0;
    }

    private void checkDelete(KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_DELETE && isListItemSelected()) {
            deleteUserDefinedFileType();
        }
    }

    private class ButtonEnabler implements ListSelectionListener {

        @Override
        public void valueChanged(ListSelectionEvent e) {
            if (!e.getValueIsAdjusting()) {
                boolean itemSelected = isListItemSelected();

                buttonDelete.setEnabled(itemSelected);
                buttonEdit.setEnabled(itemSelected);
            }
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        labelInfo = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        buttonEdit = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();

        list.setModel(new ListModelUserDefinedFileTypes());
        list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMouseClicked(evt);
            }
        });
        list.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                listKeyPressed(evt);
            }
        });
        scrollPane.setViewportView(list);

        labelInfo.setForeground(new java.awt.Color(255, 0, 0));
        labelInfo.setText(JptBundle.INSTANCE.getString("UserDefinedFileTypesPanel.labelInfo.text")); // NOI18N

        buttonAdd.setText(JptBundle.INSTANCE.getString("UserDefinedFileTypesPanel.buttonAdd.text")); // NOI18N
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonEdit.setText(JptBundle.INSTANCE.getString("UserDefinedFileTypesPanel.buttonEdit.text")); // NOI18N
        buttonEdit.setEnabled(false);
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        buttonDelete.setText(JptBundle.INSTANCE.getString("UserDefinedFileTypesPanel.buttonDelete.text")); // NOI18N
        buttonDelete.setEnabled(false);
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonDelete))
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelInfo)
                .addContainerGap())
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonAdd, buttonDelete, buttonEdit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInfo)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd)
                    .addComponent(buttonEdit)
                    .addComponent(buttonDelete)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        addUserDefinedFileType();
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        editUserDefinedFileType();
    }//GEN-LAST:event_buttonEditActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        deleteUserDefinedFileType();
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void listKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_listKeyPressed
        checkDelete(evt);
    }//GEN-LAST:event_listKeyPressed

    private void listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMouseClicked
        editClickedUserDefinedFileType(evt);
    }//GEN-LAST:event_listMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JList list;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
