package org.jphototagger.program.module.editmetadata;

import org.jphototagger.lib.swing.PanelExt;

/**
 * @author Elmar Baumann
 */
class EditMetaDataPanelsWrapperPanel extends PanelExt {

    private static final long serialVersionUID = 1L;
    private final transient EditMetaDataPanels editMetadtaPanels;

    EditMetaDataPanelsWrapperPanel() {
        initComponents();
        editMetadtaPanels = new EditMetaDataPanels(panelEditMetadata);
    }

    EditMetaDataPanels getEditMetadtaPanels() {
        return editMetadtaPanels;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        scrollPaneEditMetadata = org.jphototagger.resources.UiFactory.scrollPane();
        panelEditMetadata = org.jphototagger.resources.UiFactory.panel();

        setName("Edit Metadata Container"); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        panelEditMetadata.setLayout(new java.awt.GridBagLayout());
        scrollPaneEditMetadata.setViewportView(panelEditMetadata);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(scrollPaneEditMetadata, gridBagConstraints);
    }//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelEditMetadata;
    private javax.swing.JScrollPane scrollPaneEditMetadata;
    // End of variables declaration//GEN-END:variables
}
