package org.jphototagger.program.view.dialogs;

import org.jphototagger.program.resource.GUI;
import org.jphototagger.program.resource.JptBundle;
import org.jphototagger.program.UserSettings;
import org.jphototagger.program.view.panels.AdvancedSearchPanel;
import org.jphototagger.lib.dialog.Dialog;

/**
 * Nicht modaler Dialog für eine erweiterte Suche.
 *
 * @author Elmar Baumann
 */
public final class AdvancedSearchDialog extends Dialog
        implements AdvancedSearchPanel.NameListener {
    public static final AdvancedSearchDialog INSTANCE =
        new AdvancedSearchDialog(false);
    private static final long serialVersionUID = -7381253840654600441L;

    private AdvancedSearchDialog(boolean modal) {
        super(GUI.getAppFrame(), modal,
              UserSettings.INSTANCE.getSettings(), null);
        initComponents();
        panel.addNameListener(this);
        setHelpContentsUrl(JptBundle.INSTANCE.getString("Help.Url.Contents"));
    }

    @Override
    public void setVisible(boolean visible) {
        if (visible) {
            panel.readProperties();
            setSearchName(panel.getSearchName());
        }

        super.setVisible(visible);
    }

    private void beforeWindowClosing() {
        panel.writeProperties();
        panel.willDispose();
        setVisible(false);
    }

    public AdvancedSearchPanel getPanel() {
        return panel;
    }

    @Override
    protected void help() {
        help(JptBundle.INSTANCE.getString("Help.Url.AdvancedSearchDialog"));
    }

    @Override
    protected void escape() {
        beforeWindowClosing();
    }

    public AdvancedSearchPanel getAdvancedSearchPanel() {
        return panel;
    }

    @Override
    public void nameChanged(String name) {
        if (name == null) {
            throw new NullPointerException("name == null");
        }

        setSearchName(name);
    }

    private void setSearchName(String name) {
        setTitle(JptBundle.INSTANCE.getString(
                "AdvancedSearchDialog.TitlePrefix") + ": " + name);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        panel = new org.jphototagger.program.view.panels.AdvancedSearchPanel();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(JptBundle.INSTANCE.getString("AdvancedSearchDialog.title"));    // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout layout =
            new javax.swing.GroupLayout(getContentPane());

        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                layout.createSequentialGroup().addContainerGap().addComponent(
                    panel, javax.swing.GroupLayout.DEFAULT_SIZE, 595,
                    Short.MAX_VALUE).addContainerGap()));
        layout.setVerticalGroup(
            layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                panel, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        pack();
    }    // </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        beforeWindowClosing();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                AdvancedSearchDialog dialog = new AdvancedSearchDialog(true);

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jphototagger.program.view.panels.AdvancedSearchPanel panel;

    // End of variables declaration//GEN-END:variables
}
