package org.jphototagger.program.view.dialogs;

import org.jphototagger.program.resource.GUI;
import org.jphototagger.program.resource.JptBundle;
import org.jphototagger.program.UserSettings;
import org.jphototagger.program.view.panels.ExportImportPanel;
import org.jphototagger.program.view.panels.ExportImportPanel.ExportImportListener;
import org.jphototagger.lib.dialog.Dialog;

/**
 *
 * @author Elmar Baumann
 */
public class ExportImportDialog extends Dialog implements ExportImportListener {
    private static final long               serialVersionUID =
        8937656035473070405L;
    private final ExportImportPanel.Context context;

    public ExportImportDialog(ExportImportPanel.Context context) {
        super(GUI.getAppFrame(), UserSettings.INSTANCE.getSettings(),
              "ExportImportDialog");

        if (context == null) {
            throw new NullPointerException("context == null");
        }

        this.context = context;
        initComponents();
        postInitComponents();
    }

    private void postInitComponents() {
        setTitle(context.equals(ExportImportPanel.Context.EXPORT)
                 ? JptBundle.INSTANCE.getString(
                     "ExportImportDialog.Title.Export")
                 : JptBundle.INSTANCE.getString(
                     "ExportImportDialog.Title.Import"));
        setHelpContentsUrl(JptBundle.INSTANCE.getString("Help.Url.Contents"));
        setHelpPageUrl(context.equals(ExportImportPanel.Context.EXPORT)
                       ? JptBundle.INSTANCE.getString(
                           "Help.Url.ExportImportDialog.Export")
                       : JptBundle.INSTANCE.getString(
                           "Help.Url.ExportImportDialog.Import"));
        panelExportImport.setContext(context);
        panelExportImport.addListener(this);
    }

    @Override
    public void done() {
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelExportImport = new org.jphototagger.program.view.panels.ExportImportPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        panelExportImport.setName("panelExportImport"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelExportImport, javax.swing.GroupLayout.PREFERRED_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelExportImport, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ExportImportDialog dialog =
                    new ExportImportDialog(ExportImportPanel.Context.EXPORT);

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jphototagger.program.view.panels.ExportImportPanel panelExportImport;
    // End of variables declaration//GEN-END:variables
}
