package org.jphototagger.program.module.wordsets;

import java.awt.Color;
import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.JLabel;

import org.openide.util.Lookup;

import org.jphototagger.domain.repository.WordsetsRepository;
import org.jphototagger.domain.wordsets.Wordset;
import org.jphototagger.lib.swing.util.ComponentUtil;

/**
 * @author Elmar Baumann
 */
public class WordsetsPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private Wordset selectedWordset;
    private final List<JLabel> wordLabels = new ArrayList<JLabel>();

    public WordsetsPanel() {
        initComponents();
        postInitComponents();
    }

    private void postInitComponents() {
        setWordsOfSelectedWordsetName();
    }

    private void setWordsOfSelectedWordsetName() {
        panelWords.removeAll();
        wordLabels.clear();
        WordsetsRepository repository = Lookup.getDefault().lookup(WordsetsRepository.class);
        if (repository != null) {
            String wordsetName = (String) comboBoxWordsetNames.getSelectedItem();
            if (wordsetName != null) {
                selectedWordset = repository.find(wordsetName);
                if (selectedWordset != null) {
                    setWordsOfSelectedWordset();
                    repaintThisAndParent();
                }
            }
        }
    }

    private void setWordsOfSelectedWordset() {
        List<String> words = selectedWordset.getWords();
        for (String word : words) {
            addWordLabel(word);
        }
    }

    private void addWordLabel(String word) {
        JLabel labelWord = new JLabel(word);
        labelWord.setOpaque(true);
        labelWord.setForeground(Color.BLACK);
        labelWord.setBackground(Color.WHITE);
        labelWord.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        labelWord.setToolTipText(word);
        // TODO Mouse Listener: Right Click: Modify, Left Click: Add
        wordLabels.add(labelWord);
//        boolean isLastLabelInRow = wordLabels.size() % 3 == 0;
//        GridBagConstraints gbc = new GridBagConstraints();
//        gbc.weightx = 0.33;
//        gbc.gridwidth = isLastLabelInRow ? GridBagConstraints.REMAINDER : 1;
//        gbc.fill = GridBagConstraints.HORIZONTAL;
//        gbc.insets = new Insets(2, 2, 2, 2);
//        panelWords.add(labelWord, gbc);
        panelWords.add(labelWord);
    }

    private void repaintThisAndParent() {
        ComponentUtil.forceRepaint(this);
        Container parent = getParent();
        if (parent != null) {
            ComponentUtil.forceRepaint(parent);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        panelWordsets = new javax.swing.JPanel();
        comboBoxWordsetNames = new javax.swing.JComboBox();
        buttonRemoveWordset = new javax.swing.JButton();
        buttonAddWordset = new javax.swing.JButton();
        buttonEditWordset = new javax.swing.JButton();
        panelWords = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        panelWordsets.setLayout(new java.awt.GridBagLayout());

        comboBoxWordsetNames.setModel(new WordsetNamesComboBoxModel());
        comboBoxWordsetNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxWordsetNamesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelWordsets.add(comboBoxWordsetNames, gridBagConstraints);

        buttonRemoveWordset.setText("-"); // NOI18N
        buttonRemoveWordset.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        panelWordsets.add(buttonRemoveWordset, gridBagConstraints);

        buttonAddWordset.setText("+"); // NOI18N
        buttonAddWordset.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        panelWordsets.add(buttonAddWordset, gridBagConstraints);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jphototagger/program/module/wordsets/Bundle"); // NOI18N
        buttonEditWordset.setText(bundle.getString("WordsetsPanel.buttonEditWordset.text")); // NOI18N
        buttonEditWordset.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        panelWordsets.add(buttonEditWordset, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(panelWordsets, gridBagConstraints);

        panelWords.setLayout(new java.awt.GridLayout(0, 3, 2, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 5, 5, 5);
        add(panelWords, gridBagConstraints);
    }//GEN-END:initComponents

    private void comboBoxWordsetNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxWordsetNamesActionPerformed
        setWordsOfSelectedWordsetName();
    }//GEN-LAST:event_comboBoxWordsetNamesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddWordset;
    private javax.swing.JButton buttonEditWordset;
    private javax.swing.JButton buttonRemoveWordset;
    private javax.swing.JComboBox comboBoxWordsetNames;
    private javax.swing.JPanel panelWords;
    private javax.swing.JPanel panelWordsets;
    // End of variables declaration//GEN-END:variables
}
