package org.jphototagger.lib.swing;

import java.awt.Container;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintStream;
import javax.swing.JPanel;
import org.jphototagger.lib.awt.EventQueueUtil;
import org.jphototagger.lib.swing.util.MnemonicUtil;

//Most parts of code from http://unserializableone.blogspot.com/2009/01/redirecting-systemout-and-systemerr-to.html

/**
 * Writes an the system's standard output to a text area.
 *
 * Starts after calling {@code #caputure()}.
 *
 * @author Elmar Baumann
 */
public class SystemOutputPanel extends JPanel {
    private static final long  serialVersionUID = 1L;
    private static volatile int MAX_CHAR_COUNT = 100000;
    private static volatile int MAX_CHARS_EXESS  = 1000;
    private boolean  capture;

    /**
     * Default constructor.
     *
     * Call later {@code #caputure()}.
     */
    public SystemOutputPanel() {
        initComponents();
        MnemonicUtil.setMnemonics((Container) this);
    }

    /**
     * Starts to capture the system's standard output and standard error stream.
     * Redirects it via {@code System#setOut(java.io.PrintStream)} and
     * {@code System#setErr(java.io.PrintStream)}.
     */
    public synchronized void caputure() {
        if (!capture) {
            redirectSystemStreams();
        }
    }

    private void copyToClipboard() {
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(new StringSelection(textArea.getText()), null);
    }

    private void deleteText() {
        textArea.setText("");
    }

    private void updateTextArea(final String text) {
        EventQueueUtil.invokeInDispatchThread(new Runnable() {
            @Override
            public void run() {
                textArea.append(text);
                textArea.setCaretPosition(textArea.getDocument().getLength());

                int excess = textArea.getDocument().getLength() - MAX_CHAR_COUNT;

                if (excess >= MAX_CHARS_EXESS) {
                    textArea.replaceRange("", 0, excess);
                }
            }
        });
    }

    public String getOutput() {
        return textArea.getText();
    }

    private void redirectSystemStreams() {
        OutputStream out = new OutputStream() {

            @Override
            public void write(int b) throws IOException {
                updateTextArea(String.valueOf((char) b));
            }

            @Override
            public void write(byte[] b, int off, int len) throws IOException {
                updateTextArea(new String(b, off, len));
            }

            @Override
            public void write(byte[] b) throws IOException {
                write(b, 0, b.length);
            }
        };

        System.setOut(new PrintStream(out, true));
        System.setErr(new PrintStream(out, true));
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        scrollPane = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        panelButttons = new javax.swing.JPanel();
        searchPanel = new org.jphototagger.lib.swing.TextComponentSearchPanel();
        searchPanel.setSearchableTextComponent(textArea);
        buttonDelete = new javax.swing.JButton();
        buttonCopyToClipboard = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        scrollPane.setName("scrollPane"); // NOI18N
        scrollPane.setPreferredSize(org.jphototagger.resources.UiFactory.dimension(300, 200));

        textArea.setEditable(false);
        textArea.setColumns(1);
        textArea.setLineWrap(true);
        textArea.setTabSize(4);
        textArea.setWrapStyleWord(true);
        textArea.setName("textArea"); // NOI18N
        scrollPane.setViewportView(textArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(scrollPane, gridBagConstraints);

        panelButttons.setName("panelButttons"); // NOI18N
        panelButttons.setLayout(new java.awt.GridBagLayout());

        searchPanel.setName("searchPanel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        panelButttons.add(searchPanel, gridBagConstraints);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jphototagger/lib/swing/Bundle"); // NOI18N
        buttonDelete.setText(bundle.getString("SystemOutputPanel.buttonDelete.text")); // NOI18N
        buttonDelete.setToolTipText(bundle.getString("SystemOutputPanel.buttonDelete.toolTipText")); // NOI18N
        buttonDelete.setName("buttonDelete"); // NOI18N
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = org.jphototagger.resources.UiFactory.insets(0, 30, 0, 0);
        panelButttons.add(buttonDelete, gridBagConstraints);

        buttonCopyToClipboard.setText(bundle.getString("SystemOutputPanel.buttonCopyToClipboard.text")); // NOI18N
        buttonCopyToClipboard.setToolTipText(bundle.getString("SystemOutputPanel.buttonCopyToClipboard.toolTipText")); // NOI18N
        buttonCopyToClipboard.setName("buttonCopyToClipboard"); // NOI18N
        buttonCopyToClipboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCopyToClipboardActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = org.jphototagger.resources.UiFactory.insets(0, 5, 0, 0);
        panelButttons.add(buttonCopyToClipboard, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = org.jphototagger.resources.UiFactory.insets(5, 0, 0, 0);
        add(panelButttons, gridBagConstraints);
    }//GEN-END:initComponents

    private void buttonCopyToClipboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCopyToClipboardActionPerformed
        copyToClipboard();
    }//GEN-LAST:event_buttonCopyToClipboardActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        deleteText();
    }//GEN-LAST:event_buttonDeleteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCopyToClipboard;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JPanel panelButttons;
    private javax.swing.JScrollPane scrollPane;
    private org.jphototagger.lib.swing.TextComponentSearchPanel searchPanel;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
