package org.jphototagger.lib.swing;

import org.jphototagger.lib.swing.util.ComponentUtil;

/**
 * Contains a {@code org.jphototagger.lib.component.SystemOutputPanel}.
 *
 * This dialog is a singleton. It starts to capture output after calling
 * {@code #captureOutput()}.
 *
 * @author Elmar Baumann
 */
public class SystemOutputDialog extends Dialog {
    public static final SystemOutputDialog INSTANCE = new SystemOutputDialog(ComponentUtil.findFrameWithIcon());
    private static final long serialVersionUID = 1L;

    public SystemOutputDialog(java.awt.Frame parent) {
        super(parent, false);
        initComponents();
    }

    /**
     * Starts to capture the output. Calls {@code SystemOutputPanel#caputure()}.
     */
    public void captureOutput() {
        panelSystemOutput.caputure();
    }

    public String getOutput() {
        return panelSystemOutput.getOutput();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {//GEN-BEGIN:initComponents

        panelSystemOutput = new org.jphototagger.lib.swing.SystemOutputPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jphototagger/lib/swing/Bundle"); // NOI18N
        setTitle(bundle.getString("SystemOutputDialog.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelSystemOutput.setName("panelSystemOutput"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSystemOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelSystemOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                SystemOutputDialog dialog = new SystemOutputDialog(null);

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jphototagger.lib.swing.SystemOutputPanel panelSystemOutput;
    // End of variables declaration//GEN-END:variables
}
