package org.jphototagger.duplicatefinder;

import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.bushe.swing.event.EventBus;

import org.openide.util.Lookup;

import org.jphototagger.api.file.FileViewer;
import org.jphototagger.api.file.event.FileDeletedEvent;
import org.jphototagger.domain.thumbnails.ThumbnailProvider;
import org.jphototagger.lib.swing.MessageDisplayer;
import org.jphototagger.lib.util.Bundle;

/**
 * @author Elmar Baumann
 */
public class FilePanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
    private File file;

    public FilePanel() {
        initComponents();
    }

    public void setFile(File file) {
        File old = this.file;
        labelFilename.setText(file == null ? "" : file.getAbsolutePath());
        panelImage.setImage(createImage());
        setActionButtonsEnabled(file != null && file.isFile());
        firePropertyChange("file", old, this.file);
    }

    private Image createImage() {
        ThumbnailProvider thumbnailProvider = Lookup.getDefault().lookup(ThumbnailProvider.class);
        return file == null || thumbnailProvider == null
                ? null
                : thumbnailProvider.getThumbnail(file);
    }

    public File getFile() {
        return file;
    }

    private void setActionButtonsEnabled(boolean enabled) {
        buttonDeleteFile.setEnabled(enabled);
        buttonViewFile.setEnabled(enabled);
    }

    private void viewFile() {
        if (file == null) {
            return;
        }
        FileViewer fileViewer = Lookup.getDefault().lookup(FileViewer.class);
        if (fileViewer != null) {
            fileViewer.view(file);
        }
    }

    private void deleteFile() {
        if (file == null) {
            return;
        }
        String confirmMessage = Bundle.getString(FilePanel.class, "FilePanel.Confirm.Delete", file);
        if (MessageDisplayer.confirmYesNo(this, confirmMessage)) {
            boolean deleted = file.delete();
            if (deleted) {
                EventBus.publish(new FileDeletedEvent(this, file));
            } else {
                Logger.getLogger(FilePanel.class.getName()).log(Level.WARNING, "File ''{0}'' couldn''t be deleted", file);
                String errorMessage = Bundle.getString(FilePanel.class, "FilePanel.Error.Delete", file);
                MessageDisplayer.error(this, errorMessage);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        panelImage = new org.jphototagger.lib.swing.ImagePanel();
        labelFilename = new javax.swing.JLabel();
        panelActions = new javax.swing.JPanel();
        buttonDeleteFile = new javax.swing.JButton();
        buttonViewFile = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        panelImage.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout panelImageLayout = new javax.swing.GroupLayout(panelImage);
        panelImage.setLayout(panelImageLayout);
        panelImageLayout.setHorizontalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        panelImageLayout.setVerticalGroup(
            panelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(panelImage, gridBagConstraints);

        labelFilename.setText(" "); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(labelFilename, gridBagConstraints);

        panelActions.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        buttonDeleteFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jphototagger/duplicatefinder/delete.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jphototagger/duplicatefinder/Bundle"); // NOI18N
        buttonDeleteFile.setToolTipText(bundle.getString("FilePanel.buttonDeleteFile.toolTipText")); // NOI18N
        buttonDeleteFile.setEnabled(false);
        buttonDeleteFile.setMargin(new java.awt.Insets(2, 2, 2, 2));
        buttonDeleteFile.setPreferredSize(new java.awt.Dimension(18, 18));
        buttonDeleteFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteFileActionPerformed(evt);
            }
        });
        panelActions.add(buttonDeleteFile);

        buttonViewFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jphototagger/duplicatefinder/view.png"))); // NOI18N
        buttonViewFile.setToolTipText(bundle.getString("FilePanel.buttonViewFile.toolTipText")); // NOI18N
        buttonViewFile.setEnabled(false);
        buttonViewFile.setMargin(new java.awt.Insets(2, 2, 2, 2));
        buttonViewFile.setPreferredSize(new java.awt.Dimension(18, 18));
        buttonViewFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewFileActionPerformed(evt);
            }
        });
        panelActions.add(buttonViewFile);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        add(panelActions, gridBagConstraints);
    }//GEN-END:initComponents

    private void buttonDeleteFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteFileActionPerformed
        deleteFile();
    }//GEN-LAST:event_buttonDeleteFileActionPerformed

    private void buttonViewFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewFileActionPerformed
        viewFile();
    }//GEN-LAST:event_buttonViewFileActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDeleteFile;
    private javax.swing.JButton buttonViewFile;
    private javax.swing.JLabel labelFilename;
    private javax.swing.JPanel panelActions;
    private org.jphototagger.lib.swing.ImagePanel panelImage;
    // End of variables declaration//GEN-END:variables
}
