package de.elmar_baumann.imv.view.panels;

import de.elmar_baumann.imv.data.AutoCompleteData;
import de.elmar_baumann.imv.data.TextEntry;
import de.elmar_baumann.imv.database.metadata.Column;
import de.elmar_baumann.imv.resource.Bundle;
import de.elmar_baumann.imv.view.renderer.ListCellRendererKeywordsEdit;
import de.elmar_baumann.lib.component.InputVerifierMaxLength;
import de.elmar_baumann.lib.componentutil.ComponentUtil;
import de.elmar_baumann.lib.componentutil.ListUtil;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.event.ListSelectionEvent;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 * Panel zum Eingeben mehrzeiliger Texte.
 * 
 * @author  Elmar Baumann <eb@elmar-baumann.de>
 * @version 2008/09/18
 */
public class EditRepeatableTextEntryPanel extends javax.swing.JPanel implements TextEntry {

    private Column column;
    private static final String delimiter = ",";
    private AutoCompleteData autoCompleteData;
    private DefaultListModel model = new DefaultListModel();
    private boolean editable = true;
    private boolean dirty = false;

    public EditRepeatableTextEntryPanel(Column column) {
        this.column = column;
        initComponents();
        postInitComponents();
    }

    private void postInitComponents() {
        textFieldInput.setInputVerifier(new InputVerifierMaxLength(column.getLength()));
        setPropmt();
    }

    private void setPropmt() {
        labelPrompt.setText(column.getDescription());
    }

    @Override
    public void setAutocomplete() {
        autoCompleteData = new AutoCompleteData(column);
        AutoCompleteDecorator.decorate(
            textFieldInput,
            autoCompleteData.getList(),
            false);
    }

    public AutoCompleteData getAutoCompleteData() {
        return autoCompleteData;
    }

    @Override
    public String getText() {
        return ListUtil.getTokenString(model, delimiter);
    }

    @Override
    public void setText(String text) {
        ListUtil.setToken(text, delimiter, model);
        dirty = false;
        setEnabledButtons();
    }

    @Override
    public Column getColumn() {
        return column;
    }

    private void handleTextFieldKeyReleased(KeyEvent evt) {
        JComponent component = (JComponent) evt.getSource();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER &&
            component.getInputVerifier().verify(component)) {
            addInputToList();
        } else {
            setEnabledButtons();
        }
    }

    private void addInputToList() {
        String input = textFieldInput.getText();
        if (!input.isEmpty() && !model.contains(input)) {
            model.addElement(input);
            dirty = true;
            ComponentUtil.forceRepaint(getParent());
        }
    }

    @Override
    public boolean isDirty() {
        return dirty;
    }

    @Override
    public boolean isEmpty() {
        return model.isEmpty();
    }

    @Override
    public void focus() {
        textFieldInput.requestFocus();
    }

    private void removeSelectedElements() {
        Object[] values = list.getSelectedValues();
        for (Object value : values) {
            model.removeElement(value);
            dirty = true;
        }
        ComponentUtil.forceRepaint(getParent());
    }

    @Override
    public void setEditable(boolean editable) {
        this.editable = editable;
        textFieldInput.setEditable(editable);
        buttonAddInput.setEnabled(editable);
        buttonRemoveSelection.setEnabled(editable);
        list.setBackground(editable ? textFieldInput.getBackground() : getBackground());
    }

    private void handleButtonAddInputActionPerformed() {
        addInputToList();
    }

    private void handleButtonRemoveInputActionPerformed() {
        removeSelectedElements();
    }

    private void handleListValueChanged(ListSelectionEvent evt) {
        setEnabledButtons();
    }

    private void setEnabledButtons() {
        buttonAddInput.setEnabled(editable && !textFieldInput.getText().isEmpty());
        buttonRemoveSelection.setEnabled(editable && list.getSelectedIndex() >= 0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelPrompt = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        textFieldInput = new javax.swing.JTextField();
        panelButtons = new javax.swing.JPanel();
        buttonRemoveSelection = new javax.swing.JButton();
        buttonAddInput = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        labelPrompt.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        labelPrompt.setText(Bundle.getString("EditRepeatableTextEntryPanel.labelPrompt.text")); // NOI18N
        labelPrompt.setToolTipText(column.getLongerDescription());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(labelPrompt, gridBagConstraints);

        scrollPane.setMinimumSize(new java.awt.Dimension(22, 44));

        list.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        list.setModel(model);
        list.setToolTipText(Bundle.getString("EditRepeatableTextEntryPanel.list.toolTipText")); // NOI18N
        list.setCellRenderer(new ListCellRendererKeywordsEdit());
        list.setFocusable(false);
        list.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        list.setVisibleRowCount(-1);
        list.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listValueChanged(evt);
            }
        });
        scrollPane.setViewportView(list);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(scrollPane, gridBagConstraints);

        textFieldInput.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        textFieldInput.setText(Bundle.getString("EditRepeatableTextEntryPanel.textFieldInput.text")); // NOI18N
        textFieldInput.setToolTipText(Bundle.getString("EditRepeatableTextEntryPanel.textFieldInput.toolTipText")); // NOI18N
        textFieldInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldInputKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(textFieldInput, gridBagConstraints);

        panelButtons.setLayout(new java.awt.GridLayout(2, 1));

        buttonRemoveSelection.setText(Bundle.getString("EditRepeatableTextEntryPanel.buttonRemoveSelection.text")); // NOI18N
        buttonRemoveSelection.setToolTipText(Bundle.getString("EditRepeatableTextEntryPanel.buttonRemoveSelection.toolTipText")); // NOI18N
        buttonRemoveSelection.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonRemoveSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveSelectionActionPerformed(evt);
            }
        });
        panelButtons.add(buttonRemoveSelection);

        buttonAddInput.setText(Bundle.getString("EditRepeatableTextEntryPanel.buttonAddInput.text")); // NOI18N
        buttonAddInput.setToolTipText(Bundle.getString("EditRepeatableTextEntryPanel.buttonAddInput.toolTipText")); // NOI18N
        buttonAddInput.setMargin(new java.awt.Insets(0, 0, 0, 0));
        buttonAddInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddInputActionPerformed(evt);
            }
        });
        panelButtons.add(buttonAddInput);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 1, 2);
        add(panelButtons, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void textFieldInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldInputKeyReleased
    handleTextFieldKeyReleased(evt);
}//GEN-LAST:event_textFieldInputKeyReleased

private void buttonAddInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddInputActionPerformed
    handleButtonAddInputActionPerformed();
}//GEN-LAST:event_buttonAddInputActionPerformed

private void buttonRemoveSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveSelectionActionPerformed
    handleButtonRemoveInputActionPerformed();
}//GEN-LAST:event_buttonRemoveSelectionActionPerformed

private void listValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listValueChanged
    handleListValueChanged(evt);
}//GEN-LAST:event_listValueChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddInput;
    private javax.swing.JButton buttonRemoveSelection;
    private javax.swing.JLabel labelPrompt;
    private javax.swing.JList list;
    private javax.swing.JPanel panelButtons;
    private javax.swing.JScrollPane scrollPane;
    public javax.swing.JTextField textFieldInput;
    // End of variables declaration//GEN-END:variables
}
