package org.jphototagger.exif.kmlexport;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JCheckBox;

import org.openide.util.Lookup;

import org.jphototagger.api.preferences.Preferences;
import org.jphototagger.exif.ExifPreferencesKeys;

/**
 * @author Elmar Baumann
 */
public class ExportGPSToKMLSettingsPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    public ExportGPSToKMLSettingsPanel() {
        initComponents();
        postInitComponents();
    }

    private void postInitComponents() {
        readAddFilenameToGpsLocationExport();
    }

    private void readAddFilenameToGpsLocationExport() {
        Preferences preferences = Lookup.getDefault().lookup(Preferences.class);
        boolean add = preferences.getBoolean(ExifPreferencesKeys.KEY_GPS_ADD_FILENAME_TO_GPS_LOCATION_EXPORT);

        checkBoxAddFilenameToGpsLocationExport.setSelected(add);
    }

    private void storeAddFilenameToGpsLocationExport() {
        Preferences preferences = Lookup.getDefault().lookup(Preferences.class);
        boolean add = checkBoxAddFilenameToGpsLocationExport.isSelected();

        preferences.setBoolean(ExifPreferencesKeys.KEY_GPS_ADD_FILENAME_TO_GPS_LOCATION_EXPORT, add);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        checkBoxAddFilenameToGpsLocationExport = new JCheckBox();

        setName("Form"); // NOI18N

        ResourceBundle bundle = ResourceBundle.getBundle("org/jphototagger/exif/kmlexport/Bundle"); // NOI18N
        checkBoxAddFilenameToGpsLocationExport.setText(bundle.getString("ExportGPSToKMLSettingsPanel.checkBoxAddFilenameToGpsLocationExport.text")); // NOI18N
        checkBoxAddFilenameToGpsLocationExport.setName("checkBoxAddFilenameToGpsLocationExport"); // NOI18N
        checkBoxAddFilenameToGpsLocationExport.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                checkBoxAddFilenameToGpsLocationExportActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxAddFilenameToGpsLocationExport)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkBoxAddFilenameToGpsLocationExport)
                .addContainerGap(52, Short.MAX_VALUE))
        );
    }//GEN-END:initComponents

    private void checkBoxAddFilenameToGpsLocationExportActionPerformed(ActionEvent evt) {//GEN-FIRST:event_checkBoxAddFilenameToGpsLocationExportActionPerformed
        storeAddFilenameToGpsLocationExport();
    }//GEN-LAST:event_checkBoxAddFilenameToGpsLocationExportActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JCheckBox checkBoxAddFilenameToGpsLocationExport;
    // End of variables declaration//GEN-END:variables
}
