package org.jphototagger.exif.kmlexport;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ResourceBundle;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jphototagger.api.preferences.Preferences;
import org.jphototagger.exif.ExifPreferencesKeys;
import org.openide.util.Lookup;

/**
 * @author Elmar Baumann
 */
public class ExportGPSToKMLSettingsPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;

    public ExportGPSToKMLSettingsPanel() {
        initComponents();
        postInitComponents();
    }

    private void postInitComponents() {
        readAddFilenameToGpsLocationExport();
    }

    private void readAddFilenameToGpsLocationExport() {
        Preferences preferences = Lookup.getDefault().lookup(Preferences.class);
        boolean add = preferences.getBoolean(ExifPreferencesKeys.KEY_GPS_ADD_FILENAME_TO_GPS_LOCATION_EXPORT);

        checkBoxAddFilenameToGpsLocationExport.setSelected(add);
    }

    private void storeAddFilenameToGpsLocationExport() {
        Preferences preferences = Lookup.getDefault().lookup(Preferences.class);
        boolean add = checkBoxAddFilenameToGpsLocationExport.isSelected();

        preferences.setBoolean(ExifPreferencesKeys.KEY_GPS_ADD_FILENAME_TO_GPS_LOCATION_EXPORT, add);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        GridBagConstraints gridBagConstraints;

        checkBoxAddFilenameToGpsLocationExport = new JCheckBox();
        panelFill = new JPanel();
        panelVersion = new JPanel();
        labelVersion = new JLabel();

        setName("Form"); // NOI18N
        setLayout(new GridBagLayout());

        ResourceBundle bundle = ResourceBundle.getBundle("org/jphototagger/exif/kmlexport/Bundle"); // NOI18N
        checkBoxAddFilenameToGpsLocationExport.setText(bundle.getString("ExportGPSToKMLSettingsPanel.checkBoxAddFilenameToGpsLocationExport.text")); // NOI18N
        checkBoxAddFilenameToGpsLocationExport.setName("checkBoxAddFilenameToGpsLocationExport"); // NOI18N
        checkBoxAddFilenameToGpsLocationExport.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                checkBoxAddFilenameToGpsLocationExportActionPerformed(evt);
            }
        });
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridwidth = GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(10, 10, 0, 10);
        add(checkBoxAddFilenameToGpsLocationExport, gridBagConstraints);

        panelFill.setName("panelFill"); // NOI18N

        GroupLayout panelFillLayout = new GroupLayout(panelFill);
        panelFill.setLayout(panelFillLayout);
        panelFillLayout.setHorizontalGroup(
            panelFillLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        panelFillLayout.setVerticalGroup(
            panelFillLayout.createParallelGroup(Alignment.LEADING)
            .addGap(0, 61, Short.MAX_VALUE)
        );

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridwidth = GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(panelFill, gridBagConstraints);

        panelVersion.setName("panelVersion"); // NOI18N
        panelVersion.setLayout(new GridBagLayout());

        labelVersion.setText(bundle.getString("ExportGPSToKMLSettingsPanel.panelVersion.text")); // NOI18N
        labelVersion.setName("panelVersion"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        panelVersion.add(labelVersion, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridwidth = GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(10, 10, 10, 10);
        add(panelVersion, gridBagConstraints);
    }//GEN-END:initComponents

    private void checkBoxAddFilenameToGpsLocationExportActionPerformed(ActionEvent evt) {//GEN-FIRST:event_checkBoxAddFilenameToGpsLocationExportActionPerformed
        storeAddFilenameToGpsLocationExport();
    }//GEN-LAST:event_checkBoxAddFilenameToGpsLocationExportActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JCheckBox checkBoxAddFilenameToGpsLocationExport;
    private JLabel labelVersion;
    private JPanel panelFill;
    private JPanel panelVersion;
    // End of variables declaration//GEN-END:variables
}
