package org.jphototagger.program.module.search;

import org.jphototagger.lib.dialog.Dialog;
import org.jphototagger.lib.util.Bundle;
import org.jphototagger.program.resource.GUI;
import org.jphototagger.program.view.panels.NameListener;

/**
 * Nicht modaler Dialog für eine erweiterte Suche.
 *
 * @author Elmar Baumann
 */
public final class AdvancedSearchDialog extends Dialog implements NameListener {
    public static final AdvancedSearchDialog INSTANCE = new AdvancedSearchDialog(false);
    private static final long serialVersionUID = -7381253840654600441L;

    private AdvancedSearchDialog(boolean modal) {
        super(GUI.getAppFrame(), modal);
        initComponents();
        postInitComponents();
    }

    private void postInitComponents() {
        panel.addNameListener(this);
        setHelpContentsUrl("/org/jphototagger/program/resource/doc/de/contents.xml");
    }

    @Override
    public void setVisible(boolean visible) {
        if (visible) {
            panel.restore();
            setSearchName(panel.getSearchName());
        }

        super.setVisible(visible);
    }

    private void beforeWindowClosing() {
        panel.persist();
        panel.willDispose();
        setVisible(false);
    }

    public AdvancedSearchPanel getPanel() {
        return panel;
    }

    @Override
    protected void help() {
        help("advanced_search.html");
    }

    @Override
    protected void escape() {
        beforeWindowClosing();
    }

    public AdvancedSearchPanel getAdvancedSearchPanel() {
        return panel;
    }

    @Override
    public void nameChanged(String name) {
        if (name == null) {
            throw new NullPointerException("name == null");
        }

        setSearchName(name);
    }

    private void setSearchName(String name) {
        setTitle(Bundle.getString(AdvancedSearchDialog.class, "AdvancedSearchDialog.TitlePrefix") + ": " + name);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {//GEN-BEGIN:initComponents

        panel = new org.jphototagger.program.module.search.AdvancedSearchPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jphototagger/program/module/search/Bundle"); // NOI18N
        setTitle(bundle.getString("AdvancedSearchDialog.title")); // NOI18N
        setName("Form"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel.setName("panel"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        beforeWindowClosing();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                AdvancedSearchDialog dialog = new AdvancedSearchDialog(true);

                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jphototagger.program.module.search.AdvancedSearchPanel panel;
    // End of variables declaration//GEN-END:variables
}
