package org.jphototagger.plugin.flickrupload;

import org.jphototagger.lib.help.HelpUtil;
import org.jphototagger.lib.swing.util.MnemonicUtil;

/**
 * @author Elmar Baumann
 */
public class SettingsPanel extends javax.swing.JPanel {
    private static final long serialVersionUID = 1L;
    private transient Settings settings = new Settings();

    public SettingsPanel() {
        initComponents();
        readSettings();
        MnemonicUtil.setMnemonics(this);
    }

    private void deleteToken() {
        new Authorization().deleteToken();
    }

    private void readSettings() {
        checkBoxDcDescription.setSelected(settings.isAddDcDescription());
        checkBoxDcSubjects.setSelected(settings.isAddDcSubjects());
        checkBoxPhotoshopHeadline.setSelected(settings.isAddPhotoshopHeadline());
    }

    private void showHelp() {
        HelpUtil.displayHelp("/org/jphototagger/plugin/flickrupload/help/index.html");
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrivileges = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        buttonDeleteToken = new javax.swing.JButton();
        panelXmp = new javax.swing.JPanel();
        checkBoxDcSubjects = new javax.swing.JCheckBox();
        checkBoxPhotoshopHeadline = new javax.swing.JCheckBox();
        checkBoxDcDescription = new javax.swing.JCheckBox();
        panelFill = new javax.swing.JPanel();
        panelVersion = new javax.swing.JPanel();
        labelVersionInfo = new javax.swing.JLabel();
        buttonHelp = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        panelPrivileges.setName("panelPrivileges"); // NOI18N
        panelPrivileges.setLayout(new java.awt.GridBagLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/jphototagger/plugin/flickrupload/Bundle"); // NOI18N
        label.setText(bundle.getString("SettingsPanel.label.text")); // NOI18N
        label.setName("label"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        panelPrivileges.add(label, gridBagConstraints);

        buttonDeleteToken.setText(bundle.getString("SettingsPanel.buttonDeleteToken.text")); // NOI18N
        buttonDeleteToken.setName("buttonDeleteToken"); // NOI18N
        buttonDeleteToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteTokenActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        panelPrivileges.add(buttonDeleteToken, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        add(panelPrivileges, gridBagConstraints);

        panelXmp.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("SettingsPanel.panelXmp.border.title"))); // NOI18N
        panelXmp.setName("panelXmp"); // NOI18N

        checkBoxDcSubjects.setText(bundle.getString("SettingsPanel.checkBoxDcSubjects.text")); // NOI18N
        checkBoxDcSubjects.setName("checkBoxDcSubjects"); // NOI18N
        checkBoxDcSubjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxDcSubjectsActionPerformed(evt);
            }
        });

        checkBoxPhotoshopHeadline.setText(bundle.getString("SettingsPanel.checkBoxPhotoshopHeadline.text")); // NOI18N
        checkBoxPhotoshopHeadline.setName("checkBoxPhotoshopHeadline"); // NOI18N
        checkBoxPhotoshopHeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPhotoshopHeadlineActionPerformed(evt);
            }
        });

        checkBoxDcDescription.setText(bundle.getString("SettingsPanel.checkBoxDcDescription.text")); // NOI18N
        checkBoxDcDescription.setName("checkBoxDcDescription"); // NOI18N
        checkBoxDcDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxDcDescriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelXmpLayout = new javax.swing.GroupLayout(panelXmp);
        panelXmp.setLayout(panelXmpLayout);
        panelXmpLayout.setHorizontalGroup(
            panelXmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXmpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelXmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBoxDcDescription)
                    .addComponent(checkBoxDcSubjects)
                    .addComponent(checkBoxPhotoshopHeadline))
                .addContainerGap(410, Short.MAX_VALUE))
        );
        panelXmpLayout.setVerticalGroup(
            panelXmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelXmpLayout.createSequentialGroup()
                .addComponent(checkBoxDcSubjects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxPhotoshopHeadline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxDcDescription)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        add(panelXmp, gridBagConstraints);

        panelFill.setName("panelFill"); // NOI18N

        javax.swing.GroupLayout panelFillLayout = new javax.swing.GroupLayout(panelFill);
        panelFill.setLayout(panelFillLayout);
        panelFillLayout.setHorizontalGroup(
            panelFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        panelFillLayout.setVerticalGroup(
            panelFillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(panelFill, gridBagConstraints);

        panelVersion.setName("panelVersion"); // NOI18N
        panelVersion.setLayout(new java.awt.GridBagLayout());

        labelVersionInfo.setText(bundle.getString("SettingsPanel.labelVersionInfo.text")); // NOI18N
        labelVersionInfo.setName("labelVersionInfo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        panelVersion.add(labelVersionInfo, gridBagConstraints);

        buttonHelp.setText(bundle.getString("SettingsPanel.buttonHelp.text")); // NOI18N
        buttonHelp.setName("buttonHelp"); // NOI18N
        buttonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHelpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        panelVersion.add(buttonHelp, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(panelVersion, gridBagConstraints);
    }//GEN-END:initComponents

    private void buttonDeleteTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteTokenActionPerformed
        deleteToken();
    }//GEN-LAST:event_buttonDeleteTokenActionPerformed

    private void checkBoxDcSubjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxDcSubjectsActionPerformed
        if (settings != null) {
            settings.setAddDcSubjects(checkBoxDcSubjects.isSelected());
        }
    }//GEN-LAST:event_checkBoxDcSubjectsActionPerformed

    private void checkBoxPhotoshopHeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPhotoshopHeadlineActionPerformed
        if (settings != null) {
            settings.setAddPhotoshopHeadline(
                    checkBoxPhotoshopHeadline.isSelected());
        }
    }//GEN-LAST:event_checkBoxPhotoshopHeadlineActionPerformed

    private void checkBoxDcDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxDcDescriptionActionPerformed
        if (settings != null) {
            settings.setAddDcDescription(checkBoxDcDescription.isSelected());
        }
    }//GEN-LAST:event_checkBoxDcDescriptionActionPerformed

    private void buttonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHelpActionPerformed
        showHelp();
    }//GEN-LAST:event_buttonHelpActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDeleteToken;
    private javax.swing.JButton buttonHelp;
    private javax.swing.JCheckBox checkBoxDcDescription;
    private javax.swing.JCheckBox checkBoxDcSubjects;
    private javax.swing.JCheckBox checkBoxPhotoshopHeadline;
    private javax.swing.JLabel label;
    private javax.swing.JLabel labelVersionInfo;
    private javax.swing.JPanel panelFill;
    private javax.swing.JPanel panelPrivileges;
    private javax.swing.JPanel panelVersion;
    private javax.swing.JPanel panelXmp;
    // End of variables declaration//GEN-END:variables
}
